version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: base
      MYSQL_ROOT_PASSWORD: 123456
  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456