server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types:
    - application/json
    - application/xml
    - text/html
    - text/xml
    - text/plain
spring:
  application:  
    name: service-web
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/base
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    initialization-mode: always
    sql-script-encoding: utf-8
#    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: create
static-resource:
  root-path: /Users/cma2/Documents/upload
logging:
  level:
    org.springframework.web: info
    com.machao.base: debug